config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
              sessions: "users/sessions",
         registrations: "users/registrations",
   }

  root                              to:"pages#index"
  post   '/',                       to:"pages#index"
  post   'pages/guest_sign_in',     to:"pages#guest_sign_in"
  get    'pages/show'
  get    'pages/about'
  get    '/ramens/search',          to: "ramens#search"
  post   '/ramens/:ramen_id/likes', to: "likes#create"
  delete '/ramens/:ramen_id/likes', to: "likes#destroy"

  resources :users,  only: [:show, :index]
  resources :ramens, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/models/ramen.rb
class Ramen < ApplicationRecord
  belongs_to       :user
  has_many         :likes, dependent: :destroy
  has_many         :like_users, through: :likes, source: :user, dependent: :destroy
  has_one_attached :photo, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  validates :store,        length: { maximum: 20 },  presence: true
  validates :price,        length: { maximum: 6 }
  validates :product_name, length: { maximum: 20 }
  validates :comment,      length: { maximum: 200 }, presence: true
  validates :photo,                                  presence: true

  scope :search, -> (search_params) do
    # search_paramsが空の場合以降の処理を行わない。
    return if search_params.blank?

    # パラメータを指定して検索を実行する(and条件)
    store_like(search_params[:store])
      .product_name_like(search_params[:product_name])
      .genre_is(search_params[:genre])
      .soup_is(search_params[:soup])
      .taste_is(search_params[:taste])
      .volume_is(search_params[:volume])
      .noodle_is(search_params[:noodle])
      .oily_is(search_params[:oily])
      .meat_is(search_params[:meat])
      .topping_is(search_params[:topping])
      .addictive_is(search_params[:addictive])
      .croweded_is(search_params[:croweded])
      .service_is(search_params[:service])
  end

  scope :store_like, -> (store) { where('store LIKE ?', "%#{store}%") if store.present? }
  scope :product_name_like, -> ( product_name) { where(' product_name LIKE ?', "%#{ product_name}%") if  product_name.present? }
  scope :genre_is, ->(genre) { where(genre: genre) if genre.present? }
  scope :soup_is, ->(soup) { where(soup: soup) if soup.present? }
  scope :taste_is, ->(taste) { where(taste: taste) if taste.present? }
  scope :volume_is, ->(volume) { where(volume: volume) if volume.present? }
  scope :noodle_is, ->(noodle) { where(noodle: noodle) if noodle.present? }
  scope :oily_is, ->(oily) { where(oily: oily) if oily.present? }
  scope :meat_is, ->(meat) { where(meat: meat) if meat.present? }
  scope :topping_is, ->(topping) { where(topping: topping) if topping.present? }
  scope :addictive_is, ->(addictive) { where(addictive: addictive) if addictive.present? }
  scope :croweded_is, ->(croweded) { where(croweded: croweded) if croweded.present? }
  scope :service_is, ->(service) { where(service: service) if service.present? }

end

app/controllers/ramens_controller.rb
class RamensController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @ramen = Ramen.find(params[:id])
  end

  def new
    @ramen = Ramen.new
    # @list_soup = ["醤油", "味噌"]
  end

  def create
    @ramen = current_user.ramens.build(ramen_params)
    if @ramen.save
      flash[:success] = "投稿が完了しました"
      redirect_to root_url
    else
      render new_ramen_path
    end
  end

  def edit
    @ramen = Ramen.find(params[:id])
  end

  def update
    @ramen = Ramen.find(params[:id])
    if @ramen.update(ramen_params)
      flash[:success] = "投稿が更新されました"
      redirect_to ramen_path(@ramen)
    else
      render 'edit'
    end
  end

  def destroy
    Ramen.find(params[:id]).destroy
    flash[:success] = "投稿が削除されました"
    redirect_to root_url
  end

  def search
    @search_params = ramen_search_params
    @ramens = Ramen.search(@search_params)
    @soup = ['醤油': '醤油', '味噌': '味噌', '豚骨': '豚骨', '塩': '塩', '魚介系': '魚介系', '煮干し': '煮干し', '家系': '家系', '次郎系': '次郎系', '坦々': '坦々', '辛口': '辛口', '高級食材系': '高級食材系', 'その他': 'その他']
    @ramens = @ramens.page(params[:page])
  end

  private

    def ensure_correct_user
      unless Ramen.find(params[:id]).user.id.to_i == current_user.id
        flash[:notice] = "権限がありません"
        redirect_to root_path
      end
    end

    def ramen_params
      params.require(:ramen)
            .permit(:store, :comment, :product_name, :price, :photo, :genre, :evaluation, :taste, :volume, :noodle, :oily, :meat, :topping, :addictive, :service, :croweded, :soup)
    end

    def ramen_search_params
      params.fetch(:search, {}).permit(:store, :comment, :product_name, :price, :photo, :genre, :evaluation, :taste, :volume, :noodle, :oily, :meat, :topping, :addictive, :service, :croweded, :soup)
    end
end

app/views/ramens/_ramen_column.erb
<div class="form-size field new-field">
  <div class="form-group field">
    <%= f.label :店名（※必須） %><br />
    <%= f.text_field :store, autofocus: true, autocomplete: "email", class: "form-control", placeholder: "店名を入力してください(20文字以内)" %>
  </div>

  <div class="form-group field">
    <%= f.label :商品名 %>
    <%= f.text_field :product_name, autofocus: true, autocomplete: "new-password", class: "form-control", placeholder: "商品名を入力してください(20文字以内)" %>
  </div>

  <div class="form-group field">
    <%= f.label :価格（※必須） %><br />
    <%= f.text_field :price, autofocus: true, autocomplete: "new-password", class: "form-control", placeholder: "価格を分かる範囲で数字で記入してください" %>
  </div>

  <div class="form-group field">
    <%= f.label :ラーメン画像（※必須） %><br />
    <%= f.file_field :photo, autofocus: true, class: "form-control file-field" %>
  </div>

  <div class="form-group field">
    <%= f.label :コメント（※必須） %><br />
    <%= f.text_area :comment, autofocus: true, class: "form-control text-field", rows: 5, placeholder: "ラーメンの味や感想、店内の雰囲気などを自由に記入しよう。(200文字以内)" %>
  </div>

  <%= f.label :詳細情報 , class: "detail-label" %><br />
  <div class="detail-info">
    <div class="form-group field">
      <div class="form-label">
        <%= f.label :総合評価 %><br />
      </div>
      <p>100点満点で評価をしてください。数字は直接入力できます。</p>
      <%= f.number_field(:evaluation, in: 1..100, step: '1') %>
    </div>
    <div class="form-group">
      <div class="form-label">
        <%= f.label :ジャンル %><br />
      </div>
      <%= f.select :genre, {'ラーメン': 'ラーメン', 'つけ麺': 'つけ麺', '油そば': '油そば', 'タンメン': 'タンメン', 'その他': 'その他'}, { include_blank: '選択してください'}, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <div class="form-label">
        <%= f.label :スープ %><br />
      </div>
      <%= f.select :soup, {'醤油': '醤油', '味噌': '味噌', '豚骨': '豚骨', '塩': '塩', '魚介系': '魚介系', '煮干し': '煮干し', '家系': '家系', '次郎系': '次郎系', '坦々': '坦々', '辛口': '辛口', '高級食材系': '高級食材系', 'その他': 'その他'}, { include_blank: '選択してください'}, { class: 'form-control' } %>
    </div>
    <div class="form-group field">
      <div class="form-label">
        <%= f.label :味 %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :taste, "とてもあっさり", autofocus: true, class: "form-check-input" %>
        <%= f.label :とてもあっさり, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :taste, "あっさり", autofocus: true, class: "form-check-input" %>
        <%= f.label :あっさり, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :taste, "普通", autofocus: true, class: "form-check-input" %>
        <%= f.label :普通, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :taste, "濃いめ", autofocus: true, class: "form-check-input" %>
        <%= f.label :濃いめ, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :taste, "特濃", autofocus: true, class: "form-check-input" %>
        <%= f.label :特濃, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :ボリューム %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :volume, "小盛り", autofocus: true, class: "form-check-input" %>
        <%= f.label :小盛り, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :volume, "普通", autofocus: true, class: "form-check-input" %>
        <%= f.label :普通, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :volume, "大盛り", autofocus: true, class: "form-check-input" %>
        <%= f.label :大盛り, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :volume, "特盛", autofocus: true, class: "form-check-input" %>
        <%= f.label :特盛, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :麺の太さ %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :noodle, "細麺", autofocus: true, class: "form-check-input" %>
        <%= f.label :細麺, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :noodle, "中太", autofocus: true, class: "form-check-input" %>
        <%= f.label :中太, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :noodle, "太麺", autofocus: true, class: "form-check-input" %>
        <%= f.label :太麺, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :noodle, "平打ち麺", autofocus: true, class: "form-check-input" %>
        <%= f.label :平打ち麺, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :noodle, "ちぢれ麺", autofocus: true, class: "form-check-input" %>
        <%= f.label :ちぢれ麺, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :油の量 %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :oily, "少なめ", autofocus: true, class: "form-check-input" %>
        <%= f.label :少なめ, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :oily, "普通", autofocus: true, class: "form-check-input" %>
        <%= f.label :普通, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :oily, "多め", autofocus: true, class: "form-check-input" %>
        <%= f.label :多め, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :oily, "ギトギト", autofocus: true, class: "form-check-input" %>
        <%= f.label :ギトギト, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :チャーシュー %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :meat, "なし", autofocus: true, class: "form-check-input" %>
        <%= f.label :なし, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :meat, "薄切り", autofocus: true, class: "form-check-input" %>
        <%= f.label :薄切り, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :meat, "普通", autofocus: true, class: "form-check-input" %>
        <%= f.label :普通, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :meat, "厚切り", autofocus: true, class: "form-check-input" %>
        <%= f.label :厚切り, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :meat, "極厚", autofocus: true, class: "form-check-input" %>
        <%= f.label :極厚, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :トッピングの量 %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :topping, "なし", autofocus: true, class: "form-check-input" %>
        <%= f.label :なし, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :topping, "少なめ", autofocus: true, class: "form-check-input" %>
        <%= f.label :少なめ, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :topping, "普通", autofocus: true, class: "form-check-input" %>
        <%= f.label :普通, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :topping, "多め", autofocus: true, class: "form-check-input" %>
        <%= f.label :多め, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :topping, "特盛", autofocus: true, class: "form-check-input" %>
        <%= f.label :特盛, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :中毒性 %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :addictive, "なし", autofocus: true, class: "form-check-input" %>
        <%= f.label :なし, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :addictive, "ややあり", autofocus: true, class: "form-check-input" %>
        <%= f.label :ややあり, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :addictive, "あり", autofocus: true, class: "form-check-input" %>
        <%= f.label :あり, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :addictive, "猛毒", autofocus: true, class: "form-check-input" %>
        <%= f.label :猛毒, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :混雑度 %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :croweded, "空いている", autofocus: true, class: "form-check-input" %>
        <%= f.label :空いている, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :croweded, "やや空いている", autofocus: true, class: "form-check-input" %>
        <%= f.label :やや空いている, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :croweded, "普通", autofocus: true, class: "form-check-input" %>
        <%= f.label :普通, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :croweded, "やや混雑", autofocus: true, class: "form-check-input" %>
        <%= f.label :やや混雑, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :croweded, "激混み", autofocus: true, class: "form-check-input" %>
        <%= f.label :激混み, class: "form-check-label search-label" %>
      </div>
    </div>

    <div class="form-group field">
      <div class="form-label">
        <%= f.label :サービス %><br />
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :service, "良くない", autofocus: true, class: "form-check-input" %>
        <%= f.label :良くない, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :service, "あまり良くない", autofocus: true, class: "form-check-input" %>
        <%= f.label :あまり良くない, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :service, "普通", autofocus: true, class: "form-check-input" %>
        <%= f.label :普通, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :service, "良い", autofocus: true, class: "form-check-input" %>
        <%= f.label :良い, class: "form-check-label search-label" %>
      </div>
      <div class="form-check form-check-inline form-new-check">
        <%= f.radio_button :service, "とても良い", autofocus: true, class: "form-check-input" %>
        <%= f.label :とても良い, class: "form-check-label search-label" %>
      </div>
    </div>
  </div>
  <div class="btn-center" type="submit">
    <%= f.submit "投稿", class: "btn btn-primary submit-btn" %>
  </div>
</div>

app/views/ramens/_ramen_error_messages.html.erb
<% if @ramen.errors.any? %>
<div id="error_explanation">
  <div class="ramen_error error-count">
    <%= pluralize(@ramen.errors.count, "件") %>のエラーが含まれいます。
  </div>
  <ul>
    <% @ramen.errors.full_messages.each do |msg| %>
    <li class="error-msg"><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/ramens/_ramen_post.html.erb
<div class="ramen_image">
  <%= image_tag ramen.photo.variant(gravity: "Center", resize:"400x250^",crop:"400x250+0+0").processed,alt: "ramen_image", class: "ramen_image d-block mx-auto"%>
</div>
<div class="ramen_info">
  <h3 class="ramen_store"><%= ramen.store %></h3>
  <div class="rigth-content">
    <p class="ramen_name"><%= ramen.product_name %></p>
    / <p class="ramen_price">¥ <%= ramen.price %></p>
  </div>
  <div class="ramen_comment">
    <p><%= ramen.comment %></p>
  </div>
  <div class="ramen-details">
    　<span class="detail-title">詳細情報</span>
    <ul>
      <p class="ramen-detail form-label form-show-label">総合評価
      <div class="ramen-detail-info"><%= ramen.evaluation %>点</div>
      </p>
      <p class="ramen-detail form-label form-show-label">ジャンル
      <div class="ramen-detail-info"><%= ramen.genre %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">スープ
      <div class="ramen-detail-info"><%= ramen.soup %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">味
      <div class="ramen-detail-info"><%= ramen.taste %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">ボリューム
      <div class="ramen-detail-info"><%= ramen.volume %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">麺の太さ
      <div class="ramen-detail-info"><%= ramen.noodle %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">油の量
      <div class="ramen-detail-info"><%= ramen.oily %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">チャーシュー
      <div class="ramen-detail-info"><%= ramen.meat %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">トッピングの量
      <div class="ramen-detail-info"><%= ramen.topping %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">中毒性
      <div class="ramen-detail-info"><%= ramen.addictive %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">混雑度
      <div class="ramen-detail-info"><%= ramen.croweded %></div>
      </p>
      <p class="ramen-detail form-label form-show-label">サービス
      <div class="ramen-detail-info"><%= ramen.service %></div>
      </p>
    </ul>
  </div>
  <p class="ramen-time">投稿日: <%= ramen.created_at.strftime('%Y/%m/%d') %></p>
  <% if ramen.user_id == current_user.id %>
  <div class="row">
    <div class="col col-2">
      <%= link_to "編集", edit_ramen_path(ramen), class: "btn btn-danger btn-sm ramen_btn" %>
    </div>
    <div class="col col-2">
      <%= link_to "削除", ramen_path(ramen), method: :delete,　data: { confirm: "本当に削除してもいいですか?" }, class: "btn btn-danger btn-sm ramen_btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/ramens/edit.html.erb
<% provide(:title, "投稿の編集")%>
<div class="row white-container">
  <div class="col mx-auto">
    <h2 class="title black-text-title">投稿の編集</h2>
    <div class="mx-auto" style="width: 600px;">
      <%= form_for(@ramen, url: ramen_path(@ramen)) do |f| %>
      <%= render 'ramen_error_messages'%>
      <%= render 'ramen_column', f: f %>
      <% end %>
    </div>
  </div>
</div>

app/views/ramens/new.html.erb
<% provide(:title, "新規投稿")%>
<div class="row white-container">
  <div class="col align-self-center">
    <h2 class="title black-text-title">新規投稿</h2>
    <%= form_for(@ramen, url: ramens_path) do |f| %>
    <%= render 'ramen_error_messages'%>
    <%= render 'ramen_column', f: f %>
    <% end %>
  </div>
</div>

app/views/ramens/search.html.erb
<% provide(:title, "検索") %>
<div class="row white-container">
  <div class="col align-self-center">
    <h2 class="title black-text-title">ラーメン検索</h2>
    <div class="search-brock">
      <%= render 'search_box' %>
    </div>
    <div class="row white-container">
      <div class="col align-self-center">
        <h2 class="title black-text-title">検索結果</h2>
        <%= render partial: 'pages/ramens', collection: @ramens, as: :ramen %>
      </div>
    </div>
    <div class="paginate">
      <%= paginate @ramens%>
    </div>
  </div>
</div>

app/views/ramens/show.html.erb
<% provide(:title, "投稿の詳細") %>
<div class="row white-container">
  <div class="col align-self-center">
    <h2 class="title black-text-title">投稿の詳細</h2>
    <%= render 'ramen_post', ramen: @ramen %>
  </div>
</div>