config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
              sessions: "users/sessions",
         registrations: "users/registrations",
   }

  root                              to:"pages#index"
  post   '/',                       to:"pages#index"
  post   'pages/guest_sign_in',     to:"pages#guest_sign_in"
  get    'pages/show'
  get    'pages/about'
  get    '/ramens/search',          to: "ramens#search"
  post   '/ramens/:ramen_id/likes', to: "likes#create"
  delete '/ramens/:ramen_id/likes', to: "likes#destroy"

  resources :users,  only: [:show, :index]
  resources :ramens, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/views/pages/_like.html.erb
<% if Like.find_by(user_id: current_user.id, ramen_id: ramen.id) %>
<%= link_to "/ramens/#{ramen.id}/likes", method: :delete, remote: true do %>
<p class="like-count"><i class="fas fa-heart like-btn fa-2x"><%= ramen.likes.length %></i></p>
<% end %>
<% else %>
<%= link_to "/ramens/#{ramen.id}/likes", method: :post, remote: true do %>
<p class="like-count"><i class="far fa-heart unlike-btn fa-2x"><%= ramen.likes.length %></i></p>
<% end %>
<% end %>

app/views/pages/_ramens.html.erb
<div class="col-sm-6 col-md-4 col-outline">
  <div class="ramen_image">
    <%= image_tag ramen.photo.variant(gravity: "Center", resize:"300x250^",crop:"300x250+0+0").processed,alt: "ramen_image", class: "ramen_image d-block mx-auto"%>
  </div>
  <div class="ramen_info  three_col">
    <div class="ramen_info_mini">
      <h3 class="ramen_store"><%= ramen.store %></h3>
      <div class="rigth-content">
        <p class="ramen_name"><%= ramen.product_name %></p>
        <% if ramen.price %>
        / <p class="ramen_price">¥ <%= ramen.price %></p>
        <% end %>
      </div>
    </div>
    <div class="comment_field">
      <div class="ramen_comment">
        <p><%= ramen.comment %></p>
      </div>
    </div>
    <div class="row ramen-col-bottom">
      <div class="col col-1">
        <%= link_to "詳細", ramen_path(ramen), class: "btn btn-danger btn-sm ramen_btn sm-btn" %>
      </div>
      <% if ramen.user_id == current_user.id %>
      <div class="col col-1">
        <%= link_to "編集", edit_ramen_path(ramen), class: "btn btn-danger btn-sm ramen_btn sm-btn" %>
      </div>
      <% end %>
      <div class="col col-1">
        <div id="like-<%= ramen.id %>">
          <%= render partial: "pages/like", locals: { ramen: ramen } %>
        </div>
      </div>
    </div>

    <p class="ramen-time">投稿日: <%= ramen.created_at.strftime('%Y/%m/%d') %></p>
  </div>
</div>

app/views/pages/_ramens_post.html.erb
<div class="container-fluid">
  <div class="row justify-content-start post-side-margin">
    <%= render partial: 'pages/ramens', collection: @ramens, as: :ramen %>
  </div>
  <%= paginate @ramens%>
</div>

app/views/pages/about.html.erb
<div class="jumbotron text-center">
  <div class="col align-self-center">
    <h3 class="mendou-font">あなたの人生最高の一杯をここでみつけよう</h3>
    <% unless user_signed_in? %>
    <%= link_to "はじめる", new_user_session_path, class: "btn btn-flat-border" %><br />
    <%= link_to "テストログイン", pages_guest_sign_in_path, method: :post, class: "btn btn-flat-border test-login" %>
    <% end %>
  </div>
</div>
<div class="text-center red-container">
  <h2 class="title" , id="about">ABOUT</h2>
  <p class="title-msg">
    このサービスでは、ラーメンを愛する者たちが集い<br>自分の食べたラーメンを共有することができます。<br>また、蓄積されたラーメンデータベースの中から<br>あなたが求める最高のラーメンを探し出すこともできます。
  </p>
</div>

app/views/pages/index.html.erb
<% if user_signed_in? %>
<div class="jumbotron text-center top-image-mini">
  <div class="col align-self-center">
    <h3 class="mendou-font mendou-font-mini">あなたの人生最高の一杯をここでみつけよう</h3>
    <%= link_to "検索", ramens_search_path, class: "btn btn-flat-border search-top-btn" %><br />
  </div>
</div>
<div class="row tab-container">
  <div class="container-fluid">
    <div class="row justify-content-center no-gutters">
      <div class="container tab_box">
        <ul class="tab-list">
          <li class="tab box-active">最近の投稿</li>
          <li class="tab">人気投稿</li>
        </ul>
        <div class="tabbox-contents">
          <div class="container-fluid">
            <div class="row row justify-content-center no-gutters">
              <div class="tabbox box-show">
                <%= render partial: 'pages/ramens', collection: @ramens, as: :ramen %>
              </div>
              <div class="tabbox">
                <%= render partial: 'pages/ramens', collection: @ramen_lanking, as: :ramen %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="paginate">
      <%= paginate @ramens%>
    </div>
  </div>
</div>
</div>
<%= javascript_pack_tag 'users/show' %>
<% else %>
<div class="jumbotron text-center">
  <div class="col align-self-center">
    <h3 class="mendou-font">あなたの人生最高の一杯をここでみつけよう</h3>
    <%= link_to "はじめる", new_user_session_path, class: "btn btn-flat-border" %><br />
    <%= link_to "テストログイン", pages_guest_sign_in_path, method: :post, class: "btn btn-flat-border test-login" %>
  </div>
</div>
<div class="text-center red-container">
  <h2 class="title" , id="about">ABOUT</h2>
  <p class="title-msg">
    このサービスでは、ラーメンを愛する者たちが集い<br>自分の食べたラーメンを共有することができます。<br>また、蓄積されたラーメンデータベースの中から<br>あなたが求める最高のラーメンを探し出せる。
  </p>
</div>
<% end %>

app/views/pages/show.html.erb
<h1>こんにちは、<%= current_user.username %>さん</h1>
<p>ユーザー用ページです。</p>