config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
              sessions: "users/sessions",
         registrations: "users/registrations",
   }

  root                              to:"pages#index"
  post   '/',                       to:"pages#index"
  post   'pages/guest_sign_in',     to:"pages#guest_sign_in"
  get    'pages/show'
  get    'pages/about'
  get    '/ramens/search',          to: "ramens#search"
  post   '/ramens/:ramen_id/likes', to: "likes#create"
  delete '/ramens/:ramen_id/likes', to: "likes#destroy"

  resources :users,  only: [:show, :index]
  resources :ramens, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/views/layouts/_fixed_btn.html.erb
<div class="fixed-btn">
  <a href="/ramens/new">
    <i class="far fa-edit red-icon"></i>
  </a>
</div>

app/views/layouts/_flash_msg.html.erb
<% flash.each do |key, value| %>
<div class="flash">
  <%= content_tag(:div, value, class: "#{key} alert") %>
</div>
<% end %>

app/views/layouts/_foot.html.erb
<!-- jQuery、Popper.js、Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script>
  function hamburger() {
    document.getElementById('line1').classList.toggle('line_1');
    document.getElementById('line2').classList.toggle('line_2');
    document.getElementById('line3').classList.toggle('line_3');
    document.getElementById('nav').classList.toggle('in');
  }
  document.getElementById('hamburger').addEventListener('click', function() {
    hamburger();
  });
  document.getElementById('nav').addEventListener('click', function() {
    hamburger();
  });
</script>

app/views/layouts/_footer.html.erb
<footer>
  <p>Copyright © 2021 HINAKO UCHIDA</p>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= page_title(yield(:title))%></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- viewport meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Bootstrap JavaScript-->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <!-- Font Awesome -->
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
</head>

app/views/layouts/_header.html.erb
<header>
  <div id="hamburger">
    <span class="inner_line" id="line1"></span>
    <span class="inner_line" id="line2"></span>
    <span class="inner_line" id="line3"></span>
  </div>
  <nav id="nav">
    <ul>
      <%= link_to "TOP", root_path, class: "nav-link text-danger" %>
      <%= link_to "ABOUT", pages_about_path(anchor: 'about'), class: "nav-link text-danger" %>
      <% if user_signed_in? %>
      <%= link_to "MyPage", user_path(current_user), class: "nav-link text-danger" %>
      <%= link_to "ユーザー", users_path, class: "nav-link text-danger" %>
      <%= link_to "検索", ramens_search_path, class: "btn btn-danger btn-sm nav-btn search-btn" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger btn-sm nav-btn" %>
      <% else %>
      <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-danger btn-sm nav-btn" %>
      <%= link_to "サインアップ", new_user_registration_path, class: "btn btn-danger btn-sm nav-btn" %>
      <% end %>
    </ul>
  </nav>
  <div class="navbar-image">
    <a class="navbar-brand" href="/"></a>
  </div>
</header>

app/views/layouts/_oldheader.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <%= link_to "TOP", root_path, class: "nav-link text-danger" %>
        <%= link_to "ABOUT", pages_about_path(anchor: 'about'), class: "nav-link text-danger" %>
        <% if user_signed_in? %>
        <%= link_to "MyPage", user_path(current_user), class: "nav-link text-danger" %>
        <%= link_to "ユーザー", users_path, class: "nav-link text-danger" %>
        <%= link_to "検索", ramens_search_path, class: "btn btn-danger btn-sm nav-btn search-btn" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger btn-sm nav-btn" %>
        <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-danger btn-sm nav-btn" %>
        <%= link_to "サインアップ", new_user_registration_path, class: "btn btn-danger btn-sm nav-btn" %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render "layouts/head" %>

<body>
  <%= render "layouts/header" %>
  <%= render "layouts/flash_msg" %>
  <main>

    <%= yield %>

    <%= render "layouts/fixed_btn" %>
    <%= render "layouts/footer" %>
  </main>
  <%= render "layouts/foot" %>
</body>

</html>